### ISSUE TITLE
Instructions to deploy cbws / etcd-operator

### ISSUE THREAD

**Issue by turkenh** [cbws/etcd-operator#59]
First of all, thanks a lot for maintaining etcd-operator 🎉

I already see a lot of improvements compared to original repo and want to switch using this one. However, I couldn't find instruction for installation. Existing instructions seems to still installing `coreos/etcd-operator`.  

I am especially interested in deploying via helm chart and noticed that existing chart accepts operator image as [parameter](https://github.com/helm/charts/blob/master/stable/etcd-operator/values.yaml#L44-L46), however, how can we ensure that deployment templates are still compatible?

**Comment by nvtkaszpir** [comment]
just use official helm chart from `stable/etcd-operator` and feed it with custom values file with modified images, such as:

```yaml
etcdOperator:
  priorityClassName: ""
  name: etcd-operator
  replicaCount: 1
  image:
    repository: cbws/etcd-operator
    tag: v0.10.0
    pullPolicy: Always
```

Same for backup and restore operators.
